### PR TITLE
Fix player knockback in spectators

### PR DESCRIPTION
**Pull request by mikinol**

### CODE REVIEW

**Comment by mikinol** [comment]
@Twocoolguy

**Review by Ethan-Passino — CHANGES_REQUESTED** [review]
I know it has been a while since I've been active on this project, my apologies.
Why not just add it to the already existing if statement that checks for creative mode?

**Comment by mikinol** [comment]
The reason is that the if condition for creative mode not only cancels the hit, but also removes the brick.

**Review by Ethan-Passino — APPROVED** [review]
lgtm

**Pull request merged**
